version: '3.8'

services:
  backend:
    build: ./backend
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - cassandra
      - kafka
    networks:
      - mynetwork

  frontend:
    build: ./frontend
    container_name: react_app
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - mynetwork

  cassandra:
    image: cassandra:3.11
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - mynetwork

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - mynetwork

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - mynetwork

networks:
  mynetwork:


volumes:
  cassandra_data:
